# Generated by Django 3.1.5 on 2021-01-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210119_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.TextField(max_length=254),
        ),
    ]
