# Generated by Django 3.1.5 on 2021-03-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210321_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publisher_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
